## Travis CI Configuration file

os: linux
dist: bionic
language: c

# Install dependencies
before_install:
  - sudo apt install libusb-1.0-0-dev
addons:
  apt:
    update: true

# Only grab latest git commit (no need for history)
git:
  depth: 1

script:
  - make